name: "Cronjob NLD"
on:
  workflow_dispatch:


concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  nld_job:
    name: Người Lao Động - ${{ matrix.rand_seed }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - feed_list: "https://nld.com.vn/rss/home.rss"
            readme_path: "./docs/index.md"
            rand_seed: "nld"
          - feed_list: "https://nld.com.vn/rss/thoi-su.rss"
            readme_path: "./docs/nld/thoi-su.md"
            rand_seed: "nld-thoi-su"
          - feed_list: "https://nld.com.vn/rss/quoc-te.rss"
            readme_path: "./docs/nld/quoc-te.md"
            rand_seed: "nld-quoc-te"
          - feed_list: "https://nld.com.vn/rss/lao-dong.rss"
            readme_path: "./docs/nld/lao-dong.md"
            rand_seed: "nld-lao-dong"
          - feed_list: "https://nld.com.vn/rss/ban-doc.rss"
            readme_path: "./docs/nld/ban-doc.md"
            rand_seed: "nld-ban-doc"
          - feed_list: "https://nld.com.vn/rss/net-zero.rss"
            readme_path: "./docs/nld/net-zero.md"
            rand_seed: "nld-net-zero"
          - feed_list: "https://nld.com.vn/rss/kinh-te.rss"
            readme_path: "./docs/nld/kinh-te.md"
            rand_seed: "nld-kinh-te"
          - feed_list: "https://nld.com.vn/rss/suc-khoe.rss"
            readme_path: "./docs/nld/suc-khoe.md"
            rand_seed: "nld-suc-khoe"
          - feed_list: "https://nld.com.vn/rss/giao-duc-khoa-hoc.rss"
            readme_path: "./docs/nld/giao-duc-khoa-hoc.md"
            rand_seed: "nld-giao-duc-khoa-hoc"
          - feed_list: "https://nld.com.vn/rss/phap-luat.rss"
            readme_path: "./docs/nld/phap-luat.md"
            rand_seed: "nld-phap-luat"
          - feed_list: "https://nld.com.vn/rss/van-hoa-van-nghe.rss"
            readme_path: "./docs/nld/van-hoa-van-nghe.md"
            rand_seed: "nld-van-hoa-van-nghe"
          - feed_list: "https://nld.com.vn/rss/giai-tri.rss"
            readme_path: "./docs/nld/giai-tri.md"
            rand_seed: "nld-giai-tri"
          - feed_list: "https://nld.com.vn/rss/the-thao.rss"
            readme_path: "./docs/nld/the-thao.md"
            rand_seed: "nld-the-thao"
          - feed_list: "https://nld.com.vn/rss/ai-365.rss"
            readme_path: "./docs/nld/ai-365.md"
            rand_seed: "nld-ai-365"
          - feed_list: "https://nld.com.vn/rss/du-lich-xanh.rss"
            readme_path: "./docs/nld/du-lich-xanh.md"
            rand_seed: "nld-du-lich-xanh"
          - feed_list: "https://nld.com.vn/rss/chuyen-trang-phu-nu.rss"
            readme_path: "./docs/nld/chuyen-trang-phu-nu.md"
            rand_seed: "nld-chuyen-trang-phu-nu"
          - feed_list: "https://nld.com.vn/rss/gia-dinh.rss"
            readme_path: "./docs/nld/gia-dinh.md"
            rand_seed: "nld-gia-dinh"
          - feed_list: "https://nld.com.vn/rss/dia-oc.rss"
            readme_path: "./docs/nld/dia-oc.md"
            rand_seed: "nld-dia-oc"
          - feed_list: "https://nld.com.vn/rss/thi-truong.rss"
            readme_path: "./docs/nld/thi-truong.md"
            rand_seed: "nld-thi-truong"
          - feed_list: "https://nld.com.vn/rss/doi-song.rss"
            readme_path: "./docs/nld/doi-song.md"
            rand_seed: "nld-doi-song"
          - feed_list: "https://nld.com.vn/rss/khoa-hoc.rss"
            readme_path: "./docs/nld/khoa-hoc.md"
            rand_seed: "nld-khoa-hoc"
          - feed_list: "https://nld.com.vn/rss/vung-mien.rss"
            readme_path: "./docs/nld/vung-mien.md"
            rand_seed: "nld-vung-mien"
          - feed_list: "https://nld.com.vn/rss/video.rss"
            readme_path: "./docs/nld/video.md"
            rand_seed: "nld-video"
          - feed_list: "https://nld.com.vn/rss/podcast.rss"
            readme_path: "./docs/nld/podcast.md"
            rand_seed: "nld-podcast"

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Pull in NLD news
        uses: ePlus-DEV/blog-post-workflow@v1
        with:
          retry_count: 1
          request_timeout: 15
          push_retry_count: 10
          readme_path: ${{ matrix.readme_path }}
          feed_list: ${{ matrix.feed_list }}
          committer_email: "h250694@gmail.com"
          commit_message: "Get NLD news - ${{ matrix.rand_seed }} - ${{ github.event.repository.updated_at}}"
          rand_seed: ${{ matrix.rand_seed }}
          comment_tag_name: ${{ matrix.rand_seed }}
          date_format: "HH:MM dd/mm/yyyy"
          template: "$newline- $randomEmoji(💯,🔥,💫,🚀,🌮,📝,🥳,💻,🧰,🏊,🥰,🧐,🤓,😎,🥸,🤩,🤗,🤔,🫣,🤭,🤠,👹,👺,🤡,🤖,🎃,😺,🫶,👍,💪,💄,👀,🧠,🧑‍🏫,👨‍🏫,💂,🧑‍💻,🥷,💃,🕴,💼,🎓,🐻,🐵,🙉,🦄,🦆,🦅,🦍,🦣,🐘,🦒,🦏,🐎,🦩,🐲,🌝,🌜,🌏,🌈,🌊,🎬,🎭,🚀,🚦,⛽️,🗽,🎡,🌋,🌁,💡,🕯,🪜,🧰,⚗️,🔭,🪄,🎊,🎉) [$title]($url) - $date"
          max_post_count: 60

      - name: Force Run Workflow
        if: always()
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.actions.createWorkflowDispatch({
              owner: context.repo.owner,
              repo: context.repo.repo,
              workflow_id: 'sggp.yml',
              ref: 'main',
            })
