name: "Cronjob SGGP"
on:
  workflow_dispatch:


concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  sggp_job:
    name: SGGP - ${{ matrix.rand_seed }}
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 1
      matrix:
        include:
          - feed_list: "https://www.sggp.org.vn/rss/home.rss"
            readme_path: "./docs/index.md"
            rand_seed: "sggp"
          - feed_list: "https://www.sggp.org.vn/rss/chinh-tri.rss"
            readme_path: "./docs/sggp/chinh-tri.md"
            rand_seed: "sggp-chinh-tri"
          - feed_list: "https://www.sggp.org.vn/rss/xa-hoi.rss"
            readme_path: "./docs/sggp/xa-hoi.md"
            rand_seed: "sggp-xa-hoi"
          - feed_list: "https://www.sggp.org.vn/rss/phap-luat.rss"
            readme_path: "./docs/sggp/phap-luat.md"
            rand_seed: "sggp-phap-luat"
          - feed_list: "https://www.sggp.org.vn/rss/kinh-te.rss"
            readme_path: "./docs/sggp/kinh-te.md"
            rand_seed: "sggp-kinh-te"
          - feed_list: "https://www.sggp.org.vn/rss/da-phuong-tien.rss"
            readme_path: "./docs/sggp/da-phuong-tien.md"
            rand_seed: "sggp-da-phuong-tien"
          - feed_list: "https://www.sggp.org.vn/rss/the-gioi.rss"
            readme_path: "./docs/sggp/the-gioi.md"
            rand_seed: "sggp-the-gioi"
          - feed_list: "https://www.sggp.org.vn/rss/giao-duc.rss"
            readme_path: "./docs/sggp/giao-duc.md"
            rand_seed: "sggp-giao-duc"
          - feed_list: "https://www.sggp.org.vn/rss/y-te-suc-khoe.rss"
            readme_path: "./docs/sggp/y-te-suc-khoe.md"
            rand_seed: "sggp-y-te-suc-khoe"
          - feed_list: "https://www.sggp.org.vn/rss/van-hoa-giai-tri.rss"
            readme_path: "./docs/sggp/van-hoa-giai-tri.md"
            rand_seed: "sggp-van-hoa-giai-tri"
          - feed_list: "https://www.sggp.org.vn/rss/nhip-cau-ban-doc.rss"
            readme_path: "./docs/sggp/nhip-cau-ban-doc.md"
            rand_seed: "sggp-nhip-cau-ban-doc"
          - feed_list: "https://www.sggp.org.vn/rss/khoa-hoc-cong-nghe.rss"
            readme_path: "./docs/sggp/khoa-hoc-cong-nghe.md"
            rand_seed: "sggp-khoa-hoc-cong-nghe"

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Pull in SGGP news
        uses: ePlus-DEV/blog-post-workflow@v1
        with:
          retry_count: 5
          readme_path: ${{ matrix.readme_path }}
          feed_list: ${{ matrix.feed_list }}
          committer_email: "h250694@gmail.com"
          commit_message: "Get SGGP news - ${{ matrix.rand_seed }} - ${{ github.event.repository.updated_at}}"
          rand_seed: ${{ matrix.rand_seed }}
          comment_tag_name: ${{ matrix.rand_seed }}
          date_format: "HH:MM dd/mm/yyyy"
          template: "$newline- $randomEmoji(💯,🔥,💫,🚀,🌮,📝,🥳,💻,🧰,🏊,🥰,🧐,🤓,😎,🥸,🤩,🤗,🤔,🫣,🤭,🤠,👹,👺,🤡,🤖,🎃,😺,🫶,👍,💪,💄,👀,🧠,🧑‍🏫,👨‍🏫,💂,🧑‍💻,🥷,💃,🕴,💼,🎓,🐻,🐵,🙉,🦄,🦆,🦅,🦍,🦣,🐘,🦒,🦏,🐎,🦩,🐲,🌝,🌜,🌏,🌈,🌊,🎬,🎭,🚀,🚦,⛽️,🗽,🎡,🌋,🌁,💡,🕯,🪜,🧰,⚗️,🔭,🪄,🎊,🎉) [$title]($url) - $date"
          max_post_count: 60

      - name: Force Run Workflow
        if: always()
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.actions.createWorkflowDispatch({
              owner: context.repo.owner,
              repo: context.repo.repo,
              workflow_id: 'vtc.yml',
              ref: 'main',
            })
