name: "Cronjob TuoiTre"
on:
  workflow_dispatch:


concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  tuoitre_job:
    name: Tuổi Trẻ - ${{ matrix.rand_seed }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - feed_list: "https://tuoitre.vn/rss/tin-moi-nhat.rss"
            readme_path: "./docs/index.md"
            rand_seed: "tuoitre"
          - feed_list: "https://tuoitre.vn/rss/tin-moi-nhat.rss"
            readme_path: "./docs/tuoitre/tin-moi-nhat.md"
            rand_seed: "tuoitre-tin-moi-nhat"
          - feed_list: "https://tuoitre.vn/rss/thoi-su.rss"
            readme_path: "./docs/tuoitre/thoi-su.md"
            rand_seed: "tuoitre-thoi-su"
          - feed_list: "https://tuoitre.vn/rss/the-gioi.rss"
            readme_path: "./docs/tuoitre/the-gioi.md"
            rand_seed: "tuoitre-the-gioi"
          - feed_list: "https://tuoitre.vn/rss/kinh-doanh.rss"
            readme_path: "./docs/tuoitre/kinh-doanh.md"
            rand_seed: "tuoitre-kinh-doanh"

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Pull in TuoiTre news
        uses: ePlus-DEV/blog-post-workflow@v1
        with:
          retry_count: 1
          request_timeout: 15
          push_retry_count: 10
          readme_path: ${{ matrix.readme_path }}
          feed_list: ${{ matrix.feed_list }}
          committer_email: "h250694@gmail.com"
          commit_message: "Get TuoiTre news - ${{ matrix.rand_seed }} - ${{ github.event.repository.updated_at}}"
          rand_seed: ${{ matrix.rand_seed }}
          comment_tag_name: ${{ matrix.rand_seed }}
          date_format: "HH:MM dd/mm/yyyy"
          template: "$newline- $randomEmoji(💯,🔥,💫,🚀,🌮,📝,🥳,💻,🧰,🏊,🥰,🧐,🤓,😎,🥸,🤩,🤗,🤔,🫣,🤭,🤠,👹,👺,🤡,🤖,🎃,😺,🫶,👍,💪,💄,👀,🧠,🧑‍🏫,👨‍🏫,💂,🧑‍💻,🥷,💃,🕴,💼,🎓,🐻,🐵,🙉,🦄,🦆,🦅,🦍,🦣,🐘,🦒,🦏,🐎,🦩,🐲,🌝,🌜,🌏,🌈,🌊,🎬,🎭,🚀,🚦,⛽️,🗽,🎡,🌋,🌁,💡,🕯,🪜,🧰,⚗️,🔭,🪄,🎊,🎉) [$title]($url) - $date"
          max_post_count: 60

      - name: Force Run Workflow
        if: always()
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.actions.createWorkflowDispatch({
              owner: context.repo.owner,
              repo: context.repo.repo,
              workflow_id: 'vietnamplus.yml',
              ref: 'main',
            })
